changelog:
  categories:
    - title: Features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [bug, fix]
    - title: Maintenance
      labels: [chore, refactor]
    - title: Documentation
      labels: [docs]
    - title: CI/CD
      labels: [ci, workflow]
